// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfGceeZXous1MlLf0EqkDq1xROMONR4dQ',
    appId: '1:879937882993:web:6505ace3096237a69ac4d0',
    messagingSenderId: '879937882993',
    projectId: 'fasum-app-e702b',
    authDomain: 'fasum-app-e702b.firebaseapp.com',
    storageBucket: 'fasum-app-e702b.firebasestorage.app',
    measurementId: 'G-1GXMX8Y7Z0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa4QsghMEd4vcH7SIRZMtxVLkJXwc2Z4M',
    appId: '1:879937882993:android:4d3481d6d3a355ad9ac4d0',
    messagingSenderId: '879937882993',
    projectId: 'fasum-app-e702b',
    storageBucket: 'fasum-app-e702b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGim8pFzyocwN6A-PQaZDGXJ0de4oUysI',
    appId: '1:879937882993:ios:e3f929b60b8f4b989ac4d0',
    messagingSenderId: '879937882993',
    projectId: 'fasum-app-e702b',
    storageBucket: 'fasum-app-e702b.firebasestorage.app',
    iosBundleId: 'com.example.fasum1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGim8pFzyocwN6A-PQaZDGXJ0de4oUysI',
    appId: '1:879937882993:ios:e3f929b60b8f4b989ac4d0',
    messagingSenderId: '879937882993',
    projectId: 'fasum-app-e702b',
    storageBucket: 'fasum-app-e702b.firebasestorage.app',
    iosBundleId: 'com.example.fasum1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfGceeZXous1MlLf0EqkDq1xROMONR4dQ',
    appId: '1:879937882993:web:9493fd55d1373a719ac4d0',
    messagingSenderId: '879937882993',
    projectId: 'fasum-app-e702b',
    authDomain: 'fasum-app-e702b.firebaseapp.com',
    storageBucket: 'fasum-app-e702b.firebasestorage.app',
    measurementId: 'G-VR6XHZX3L0',
  );
}
